// <auto-generated />
namespace DoAn.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class applicationuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applicationuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201910170436221_applicationuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
